import os
import sys
import time
import uuid
import logging
from pathlib import Path

# ── Third-party ───────────────────────────────────────────────────────────────
import pandas as pd
import requests
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import sacrebleu
import unicodedata

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="[%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger(__name__)

# ── Configuration ─────────────────────────────────────────────────────────────
BACKEND_URL       = "http://127.0.0.1:8000/translate"
DATASETS_DIR      = Path("dataset")
RESULTS_DIR       = Path("results")
REQUEST_TIMEOUT   = 60       # seconds
PROGRESS_INTERVAL = 10       # log every N rows
BERTSCORE_MODEL   = "bert-base-multilingual-cased"

REQUIRED_COLUMNS = {
    "input", "expected_resolved", "target_language",
    "ground_truth_translation", "emotion",
}

# ── System limitations (FIX 3) ────────────────────────────────────────────────
SYSTEM_LIMITATIONS = {
    "translation_backbone":
        "Google Translate (unofficial gtx API) — not a trained model",
    "nllb_role":
        "NLLB-600M used as fallback only, not primary translation engine",
    "emotion_conditioning":
        "Prompt-level prefix injection — not fine-tuned emotion-aware NMT",
    "coreference_coverage":
        "~200 South Asian + English names hardcoded; unknown names fall back to rule hints",
    "bleu_limitation":
        "BLEU penalises valid paraphrases — chrF and BERTScore are primary metrics",
    "ground_truth_source":
        "Ground truth may have been generated by a different/stronger model, "
        "creating an unfair surface-form mismatch penalised by BLEU",
}

RECOMMENDED_CITATIONS = [
    "Popović (2015) — chrF: character n-gram F-score for automatic MT evaluation",
    "Zhang et al. (2020) — BERTScore: Evaluating Text Generation with BERT",
    "Papineni et al. (2002) — BLEU: a Method for Automatic Evaluation of MT",
    "Costa-jussà et al. (2022) — No Language Left Behind (NLLB)",
    "Hartmann et al. (2022) — emotion-english-distilroberta-base",
]

def normalize_text(text: str) -> str:
    """
    NFC normalize + strip zero-width chars + collapse whitespace.
    Critical for Indian scripts where the same character can have
    multiple Unicode representations (composed vs decomposed).
    Without this, BERTScore and chrF both undercount matches.
    """
    text = unicodedata.normalize("NFC", str(text))
    text = text.replace("\u200b", "").replace("\ufeff", "").replace("\xa0", " ")
    text = text.replace("\u200c", "").replace("\u200d", "")   # ZWNJ, ZWJ
    text = " ".join(text.split())
    return text.strip()
# ═══════════════════════════════════════════════════════════════════════════════
# Helpers: directories, dataset discovery, CSV loading
# ═══════════════════════════════════════════════════════════════════════════════

def ensure_directories() -> None:
    DATASETS_DIR.mkdir(parents=True, exist_ok=True)
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    logger.info(f"Directories ready: '{DATASETS_DIR}/'  '{RESULTS_DIR}/'")


def discover_datasets() -> list:
    files = sorted(DATASETS_DIR.glob("english_*.csv"))
    if not files:
        logger.error(f"No CSVs found in '{DATASETS_DIR}'. Exiting.")
        sys.exit(1)
    logger.info(f"Found {len(files)} dataset(s): {[f.name for f in files]}")
    return files


def load_csv(path: Path):
    try:
        df = pd.read_csv(path, encoding="utf-8-sig")
    except Exception as exc:
        logger.error(f"Cannot read '{path.name}': {exc}")
        return None

    missing = REQUIRED_COLUMNS - set(df.columns)
    if missing:
        logger.error(f"'{path.name}' missing columns {missing}. Skipping.")
        return None

    df = df.dropna(subset=["input", "ground_truth_translation", "target_language"])
    if df.empty:
        logger.warning(f"'{path.name}' has no usable rows. Skipping.")
        return None

    logger.info(f"  Loaded '{path.name}' — {len(df)} usable rows.")
    return df


# ═══════════════════════════════════════════════════════════════════════════════
# FIX 2 — Backend call with stable session_id
# ═══════════════════════════════════════════════════════════════════════════════
def translate(
    text:        str,
    target_lang: str,
    session_id:  str,
    use_context: bool = True,
) -> str | None:
    text = str(text).replace("\u200b", "").replace("\ufeff", "").replace("\xa0", " ").strip()

    if not text or text.lower() in ("nan", "none", "null") or len(text) < 2:
        logger.warning("  Invalid text before API call — skipping.")
        return None

    payload = {
        "text":        text,
        "source_lang": "english",
        "target_lang": target_lang.lower().strip(),
        "session_id":  session_id,
        "use_context": use_context,
    }

    for attempt in range(3):   # up to 3 attempts
        try:
            resp = requests.post(
                BACKEND_URL,
                json=payload,
                timeout=REQUEST_TIMEOUT,
            )
            resp.raise_for_status()
            data = resp.json()
            break   # success — exit retry loop
        except requests.exceptions.Timeout:
            logger.warning(f"  Timeout attempt {attempt+1} for: '{text[:40]}…'")
            time.sleep(2 ** attempt)   # 1s, 2s, 4s backoff
            data = None
            continue
        except requests.exceptions.ConnectionError:
            logger.error(f"  Cannot reach backend at {BACKEND_URL}.")
            return None
        except requests.exceptions.HTTPError as exc:
            if exc.response.status_code == 429:
                logger.warning(f"  Rate limited — waiting {2**attempt}s…")
                time.sleep(2 ** attempt)
                data = None
                continue
            logger.warning(f"  HTTP {exc.response.status_code}: '{text[:40]}…'")
            return None
        except Exception as exc:
            logger.warning(f"  Unexpected error: {exc}")
            return None
    else:
        logger.warning(f"  All 3 attempts failed for: '{text[:40]}…'")
        return None

    if data is None:
        return None

    # ── DEBUG: print full response on first few calls ──────────────
    logger.debug(
        f"  Full response keys: "
        f"{list(data.keys()) if isinstance(data, dict) else type(data)}"
    )

    if isinstance(data, dict):

            for key in ("translated_text", "translated", "translation", "output", "result"):

                val = data.get(key)

                if val and isinstance(val, str) and val.strip():
                    return " ".join(val.strip().split())

                return None

    elif isinstance(data, str) and len(data.strip()) >= 2:

            return " ".join(data.strip().split())

    return None

# ═══════════════════════════════════════════════════════════════════════════════
# Metric helpers
# ═══════════════════════════════════════════════════════════════════════════════

def sentence_bleu(hyp: str, ref: str) -> float:
    try:
        return round(
            sacrebleu.sentence_bleu(
                hyp, [ref],
                smooth_method="exp",
                smooth_value=0.1,
            ).score,
            4,
        )
    except Exception:
        return 0.0


def sentence_chrf(hyp: str, ref: str) -> float:
    try:
        return round(
            sacrebleu.sentence_chrf(
                hyp, [ref],
                char_order=6,
                word_order=2,
                beta=2,
            ).score,
            4,
        )
    except Exception:
        return 0.0


def corpus_bleu(hyps: list, refs: list) -> float:
    try:
        return round(
            sacrebleu.corpus_bleu(
                hyps, [refs],
                smooth_method="exp",
                smooth_value=0.1,
                tokenize="intl",
            ).score,
            4,
        )
    except Exception:
        return 0.0


def corpus_chrf(hyps: list, refs: list) -> float:
    try:
        return round(
            sacrebleu.corpus_chrf(
                hyps, [refs],
                char_order=6,
                word_order=2,
                beta=2,
            ).score,
            4,
        )
    except Exception:
        return 0.0


def compute_bertscore(hyps: list, refs: list) -> tuple:
    """
    Compute BERTScore F1 using bert-base-multilingual-cased.
    Returns (precision%, recall%, f1%) or (0,0,0) if not installed.

    Why multilingual BERT?
    ----------------------
    bert-base-multilingual-cased supports all 11 Indian languages in
    this dataset. It computes token-level cosine similarity in a shared
    embedding space, making it robust to valid paraphrases and
    morphological variation — both common in Indian language NMT output.
    """
    try:
        from bert_score import score as bs
        P, R, F = bs(
            hyps, refs,
            model_type=BERTSCORE_MODEL,
            lang="other",
            idf=True,
            rescale_with_baseline=False,
            batch_size=8,
            verbose=False,
            device="cpu",
        )
        return (
            round(float(P.mean()) * 100, 2),
            round(float(R.mean()) * 100, 2),
            round(float(F.mean()) * 100, 2),
        )
    except ImportError:
        logger.warning("  bert-score not installed → pip install bert-score")
        return 0.0, 0.0, 0.0
    except Exception as exc:
        logger.warning(f"  BERTScore failed: {exc}")
        return 0.0, 0.0, 0.0


def _tokenize(text: str) -> set:
    """
    Space-split for Latin scripts; character-level for Indian scripts
    (Devanagari, Bengali, Tamil, Telugu, Kannada, Malayalam, Gujarati,
    Gurmukhi, Odia) which have Unicode ranges above U+0900.
    """
    if any(ord(c) > 0x0900 for c in text):
        return set(text.strip())   # character-level
    return set(text.lower().split())


def token_metrics(hyps: list, refs: list) -> tuple:
    exact      = []
    precisions = []
    recalls    = []
    f1s        = []

    for hyp, ref in zip(hyps, refs):
        ht = _tokenize(str(hyp))
        rt = _tokenize(str(ref))

        if not rt:
            precisions.append(0.0); recalls.append(0.0); f1s.append(0.0)
            continue

        tp   = len(ht & rt)
        exact.append(1 if hyp.strip() == ref.strip() else 0)
        prec = tp / len(ht) if ht else 0.0
        rec  = tp / len(rt)
        f1   = (2 * prec * rec / (prec + rec)) if (prec + rec) > 0 else 0.0
        precisions.append(prec); recalls.append(rec); f1s.append(f1)
        
    n = len(exact)
    return (
        round(sum(exact)      / n * 100, 2),
        round(sum(precisions) / n * 100, 2),
        round(sum(recalls)    / n * 100, 2),
        round(sum(f1s)        / n * 100, 2),
    )


# ═══════════════════════════════════════════════════════════════════════════════
# Core: evaluate one language dataset
# ═══════════════════════════════════════════════════════════════════════════════

def evaluate_language(df: pd.DataFrame, language: str) -> dict | None:
    """
    FIX 2: Generate one stable session_id for this entire language
    dataset.  Every row is sent with the same session_id so the
    backend builds up context sentence by sentence — exactly as a
    real user would experience the system.

    FIX 3: Pass emotion from the CSV column to the backend so the
    emotion-conditioning feature (FIX 1 in main_fixed.py) is properly
    exercised and its effect is captured in the metrics.
    """
    lang_start = time.time()
    logger.info(f"\n[START] {language}  ({len(df)} rows)")
    df = df.head(50)
    # ── FIX 2: stable session ID for this language ────────────────────────
    # Format: eval_<language>_<date>_<random>
    # Using a date+random suffix means repeated evaluation runs don't
    # share sessions (which would give the later run an unfair advantage).
    session_id = f"eval_{language.lower()}_{time.strftime('%Y%m%d')}_{uuid.uuid4().hex[:6]}"
    logger.info(f"  Session ID: {session_id}")

    rows_output: list = []
    hyps:  list = []
    refs:  list = []

    for idx, row in df.iterrows():
        raw_input = row.get("input", "")

        # Handle NaN safely
        if pd.isna(raw_input):
            logger.warning(f"  [{language}] NaN input at row {idx} — skipping.")
            continue

        # Convert to clean string
        input_text = str(raw_input)

        # Remove hidden Unicode characters
        input_text = input_text.replace("\u200b", "")
        input_text = input_text.replace("\ufeff", "")
        input_text = input_text.replace("\xa0", " ")

        # Final clean
        input_text = input_text.strip()

        # Strong validation
        if(
            not input_text
            or input_text.lower() in ("nan", "none", "null")
            or len(input_text) < 2
        ):
            logger.warning(f"  [{language}] Invalid input at row {idx} — skipping.")
            continue
        ground_truth = (
            str(row["ground_truth_translation"])
            .replace("\u200b", "")
            .replace("\ufeff", "")
            .replace("\xa0", " ")
            .strip()
        )
        target_lang  = str(row["target_language"]).strip().lower()

        if not ground_truth or ground_truth.lower() in ("nan", "none", "null"):
            logger.warning(f"  [{language}] Empty ground truth at row {idx} — skipping.")
            continue

        # ── Translate with stable session + known emotion ─────────────────
        model_output = translate(
            text        = input_text,
            target_lang = target_lang,
            session_id  = session_id,
            use_context = True,     # context ON — tests the full system
        )
        if idx % 10 == 0:
           logger.info(f"  [{language}] Processed {idx} rows")
        time.sleep(0.25)
        if model_output is None or len(model_output.strip()) < 2:
            logger.warning(f"  [{language}] Row {idx} failed (output='{model_output}') — skipping.")
            continue

        # ── Per-row metrics ───────────────────────────────────────────────
        model_output_norm = normalize_text(model_output)
        ground_truth_norm = normalize_text(ground_truth)

        s_bleu = sentence_bleu(model_output_norm, ground_truth_norm)
        s_chrf = sentence_chrf(model_output_norm, ground_truth_norm)

        rows_output.append({
            "input":        input_text,
            "ground_truth": ground_truth_norm,
            "model_output": model_output_norm,
            "bleu_score":   s_bleu,
            "chrf_score":   s_chrf,
            # BERTScore computed corpus-level only (too slow per-row)
            "bertscore_f1": None,   # filled after corpus computation
        })
        hyps.append(model_output_norm)
        refs.append(ground_truth_norm)

        done = len(rows_output)
        if done % PROGRESS_INTERVAL == 0:
            logger.info(f"  [{language}] {done} rows done…")

    if not rows_output:
        logger.warning(f"  [{language}] Zero rows completed. Skipping.")
        return None

    # ── Corpus-level metrics ──────────────────────────────────────────────
    c_bleu = corpus_bleu(hyps, refs)
    c_chrf = corpus_chrf(hyps, refs)

    logger.info(f"  [{language}] Computing BERTScore (~30s)…")
    bs_p, bs_r, bs_f1 = compute_bertscore(hyps, refs)

    accuracy, precision, recall, f1 = token_metrics(hyps, refs)

    # Fill corpus BERTScore into each row
    for r in rows_output:
        r["bertscore_f1"] = bs_f1

    # ── Console report ────────────────────────────────────────────────────
    logger.info(f"  [{language}] ─────────────────────────────")
    logger.info(f"  [{language}] BLEU      : {c_bleu:>7.2f}")
    logger.info(f"  [{language}] chrF      : {c_chrf:>7.2f}  ← primary")
    logger.info(f"  [{language}] BERTScore : {bs_f1:>7.2f}  ← primary")
    logger.info(f"  [{language}] Accuracy  : {accuracy:>7.2f}%")
    logger.info(f"  [{language}] Token F1  : {f1:>7.2f}%")
    logger.info(f"  [{language}] Session   : {session_id}")

    # ── Save per-language CSV ─────────────────────────────────────────────
    out_df = pd.DataFrame(rows_output)
    # Ensure column order
    col_order = ["input", "ground_truth", "model_output", "bleu_score", "chrf_score", "bertscore_f1"]
    out_df = out_df[[c for c in col_order if c in out_df.columns]]
    out = RESULTS_DIR / f"results_{language.lower()}.csv"
    out_df.to_csv(out, index=False, encoding="utf-8-sig")
    logger.info(f"  [{language}] Saved → {out}")
    logger.info(f"  [{language}] Completed in {round(time.time()-lang_start, 1)}s")
    return {
        "language":       language,
        "accuracy":       accuracy,
        "precision":      precision,
        "recall":         recall,
        "f1_score":       f1,
        "bleu_score":     c_bleu,
        "chrf_score":     c_chrf,
        "bertscore_p":    bs_p,
        "bertscore_r":    bs_r,
        "bertscore_f1":   bs_f1,
        "rows_evaluated": len(rows_output),
        "session_id":     session_id,
        "hyps":           hyps, 
        "refs":           refs,
    }


# ═══════════════════════════════════════════════════════════════════════════════
# Save summary CSV
# ═══════════════════════════════════════════════════════════════════════════════

def save_summary(metrics_list: list) -> None:
    cols = [
        "language", "accuracy", "precision", "recall", "f1_score",
        "bleu_score", "chrf_score", "bertscore_p", "bertscore_r",
        "bertscore_f1", "rows_evaluated", "session_id",
    ]
    # Strip internal-only keys (hyps, refs) before saving
    clean = [{k: m[k] for k in cols if k in m} for m in metrics_list]
    out   = RESULTS_DIR / "metrics_summary.csv"
    pd.DataFrame(clean, columns=cols).to_csv(out, index=False, encoding="utf-8-sig")
    logger.info(f"Metrics summary → {out}")

# ═══════════════════════════════════════════════════════════════════════════════
# Graphs
# ═══════════════════════════════════════════════════════════════════════════════

def _bar_chart(
    languages: list,
    values:    list,
    title:     str,
    ylabel:    str,
    color:     str,
    out_path:  Path,
    note:      str = "",
) -> None:
    h = max(5, len(languages) * 0.65 + 1.5)
    fig, ax = plt.subplots(figsize=(11, h))
    bars = ax.barh(languages, values, color=color, edgecolor="white",
                   height=0.55, alpha=0.88)
    for bar, val in zip(bars, values):
        ax.text(bar.get_width() + 0.5,
                bar.get_y() + bar.get_height() / 2,
                f"{val:.2f}", va="center", ha="left",
                fontsize=9, color="#333")
    ax.set_title(title, fontsize=14, fontweight="bold", pad=12)
    ax.set_xlabel(ylabel, fontsize=11)
    max_val = max(values) if values else 100
    ax.set_xlim(0, max_val * 1.18 if max_val > 0 else 100)
    ax.invert_yaxis()
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.grid(axis="x", linestyle="--", alpha=0.35)
    if note:
        fig.text(0.5, 0.01, note, ha="center", fontsize=8,
                 color="#888", style="italic")
    plt.tight_layout(rect=[0, 0.04, 1, 1])
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    logger.info(f"Graph → {out_path}")


def generate_graphs(metrics_list: list) -> None:
    if not metrics_list:
        logger.warning("No metrics to graph.")
        return

    langs    = [m["language"]      for m in metrics_list]
    accs     = [m["accuracy"]      for m in metrics_list]
    bleus    = [m["bleu_score"]    for m in metrics_list]
    chrfs    = [m["chrf_score"]    for m in metrics_list]
    berts    = [m.get("bertscore_f1", 0) for m in metrics_list]
    f1s      = [m["f1_score"]      for m in metrics_list]

    _bar_chart(langs, accs,  "Token-Exact Accuracy by Language",
               "Accuracy (%)", "#4C72B0", RESULTS_DIR / "accuracy_graph.png")

    _bar_chart(langs, bleus, "Corpus BLEU Score by Language",
               "BLEU (0–100)", "#55A868", RESULTS_DIR / "bleu_graph.png",
               note="BLEU penalises valid paraphrases — chrF and BERTScore are primary metrics for Indian languages.")

    _bar_chart(langs, chrfs, "chrF Score by Language  ★ PRIMARY METRIC",
               "chrF (0–100)", "#0060ad", RESULTS_DIR / "chrf_graph.png",
               note="chrF (Popović 2015): character-level F-score — WMT standard for morphologically-rich languages.")

    _bar_chart(langs, berts, "BERTScore F1 by Language  ★ PRIMARY METRIC",
               "BERTScore F1 (%)", "#c44e52", RESULTS_DIR / "bertscore_graph.png",
               note="BERTScore (Zhang et al. 2020): semantic similarity via bert-base-multilingual-cased.")

    _bar_chart(langs, f1s,   "Token F1 Score by Language",
               "F1 (%)", "#dd8452", RESULTS_DIR / "f1_graph.png")

    # ── Paper-ready dashboard ─────────────────────────────────────────────
    _dashboard(metrics_list, langs, bleus, chrfs, berts, f1s)


def _dashboard(metrics_list, langs, bleus, chrfs, berts, f1s):
    x     = range(len(langs))
    width = 0.20
    fig, ax = plt.subplots(figsize=(16, 6))
    ax.bar([i-1.5*width for i in x], bleus, width, label="BLEU",      color="#55A868", alpha=0.85)
    ax.bar([i-0.5*width for i in x], chrfs, width, label="chrF ★",    color="#0060ad", alpha=0.85)
    ax.bar([i+0.5*width for i in x], berts, width, label="BERTScore ★",color="#c44e52", alpha=0.85)
    ax.bar([i+1.5*width for i in x], f1s,   width, label="Token F1",  color="#dd8452", alpha=0.85)
    ax.set_xticks(list(x)); ax.set_xticklabels(langs, rotation=25, ha="right", fontsize=10)
    ax.set_ylabel("Score", fontsize=12)
    ax.set_title(
        "Context-Aware Multilingual Translation — Full Metric Comparison\n"
        "(★ = primary metrics recommended for paper)",
        fontsize=13, fontweight="bold", pad=14)
    ax.legend(fontsize=10, loc="lower right")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.grid(axis="y", linestyle="--", alpha=0.35)
    ax.set_ylim(0, 105)
    plt.tight_layout()
    out = RESULTS_DIR / "dashboard_all_metrics.png"
    fig.savefig(out, dpi=150); plt.close(fig)
    logger.info(f"Dashboard → {out}")


# ═══════════════════════════════════════════════════════════════════════════════
# FIX 3 — Console summary with honest framing
# ═══════════════════════════════════════════════════════════════════════════════

def print_summary(metrics_list: list) -> None:
    sep  = "=" * 82
    sep2 = "-" * 82
    n    = len(metrics_list)

    print()
    print(sep)
    print("  CONTEXT-AWARE MULTILINGUAL TRANSLATION — EVALUATION SUMMARY  v2.0")
    print(sep)
    print(
        f"  {'Language':<13}"
        f"{'Accuracy':>10}"
        f"{'BLEU':>8}"
        f"{'chrF★':>8}"
        f"{'BERTScore★':>12}"
        f"{'F1(tok)':>10}"
        f"{'Rows':>6}"
    )
    print(sep2)

    for m in metrics_list:
        print(
            f"  {m['language']:<13}"
            f"{str(m['accuracy'])+'%':>10}"
            f"{m['bleu_score']:>8.2f}"
            f"{m['chrf_score']:>8.2f}"
            f"{m['bertscore_f1']:>12.2f}"
            f"{m['f1_score']:>10.2f}"
            f"{m['rows_evaluated']:>6}"
        )

    if n > 0:
        print(sep2)
        print(
            f"  {'AVERAGE':<13}"
            f"{str(round(sum(m['accuracy']     for m in metrics_list)/n,1))+'%':>10}"
            f"{sum(m['bleu_score']    for m in metrics_list)/n:>8.2f}"
            f"{sum(m['chrf_score']    for m in metrics_list)/n:>8.2f}"
            f"{sum(m['bertscore_f1'] for m in metrics_list)/n:>12.2f}"
            f"{sum(m['f1_score']      for m in metrics_list)/n:>10.2f}"
        )

    print(sep)

    # ── FIX 3: Metric guidance ────────────────────────────────────────────
    print()
    print("  ★ METRIC GUIDE FOR YOUR PAPER")
    print(sep2)
    print("  BLEU      : Surface n-gram overlap. Standard but harsh.")
    print("              Reports lower than real quality for Indian languages.")
    print("              Include for comparability with prior work only.")
    print()
    print("  chrF ★    : Character-level F-score (Popović 2015).")
    print("              WMT shared-task standard for morphologically-rich")
    print("              languages (Hindi, Tamil, Telugu, Malayalam…).")
    print("              Use this as your PRIMARY metric.")
    print()
    print("  BERTScore★: Semantic similarity via bert-base-multilingual-cased")
    print("              (Zhang et al. 2020). Robust to valid paraphrases.")
    print("              Use this as your SECONDARY primary metric.")
    print()
    print("  Token F1  : Token overlap F1. Include as supplementary metric.")
    print()

    # ── FIX 3: Honest limitations block ──────────────────────────────────
    print("  ⚠  SYSTEM LIMITATIONS  (include in paper Section 5)")
    print(sep2)
    for key, val in SYSTEM_LIMITATIONS.items():
        print(f"  • {val}")
    print()

    # ── FIX 3: Suggested paper text ───────────────────────────────────────
    avg_chrf = sum(m["chrf_score"]    for m in metrics_list) / n
    avg_bert = sum(m["bertscore_f1"] for m in metrics_list) / n
    avg_bleu = sum(m["bleu_score"]    for m in metrics_list) / n

    print("  ✍  SUGGESTED PAPER TEXT (Results section)")
    print(sep2)
    print(
        f"  'We evaluate our context-aware translation system on 11 Indian\n"
        f"   languages using chrF (Popović, 2015) and BERTScore (Zhang et al.,\n"
        f"   2020) as primary metrics, and BLEU (Papineni et al., 2002) for\n"
        f"   comparability with prior work. Our system achieves an average\n"
        f"   chrF of {avg_chrf:.1f}, BERTScore F1 of {avg_bert:.1f}%, and BLEU of\n"
        f"   {avg_bleu:.1f} across all 11 languages. Evaluation was conducted\n"
        f"   with persistent session IDs to correctly test context-aware\n"
        f"   coreference resolution across sentence boundaries.'"
    )
    print()

    # ── FIX 3: Citations ──────────────────────────────────────────────────
    print("  📚  RECOMMENDED CITATIONS")
    print(sep2)
    for c in RECOMMENDED_CITATIONS:
        print(f"  [{RECOMMENDED_CITATIONS.index(c)+1}] {c}")

    print(sep)
    print()


# ═══════════════════════════════════════════════════════════════════════════════
# Entry point
# ═══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    t0 = time.time()

    ensure_directories()
    csv_files = discover_datasets()

    # Warm up backend models before timed evaluation
    logger.info("Warming up backend models…")
    try:
        wr = requests.post(
            BACKEND_URL.replace("/translate", "/warmup"),
            timeout=120,
        )
        logger.info(f"Warmup response: {wr.json()}")
    except Exception as e:
        logger.warning(f"Warmup failed (continuing anyway): {e}")

    all_metrics: list = []
    for csv_path in csv_files:
        df = load_csv(csv_path)
        if df is None:
            continue
        language = str(df["target_language"].iloc[0]).strip()
        metrics  = evaluate_language(df, language)
        if metrics:
            all_metrics.append(metrics)

    if not all_metrics:
        logger.error("No languages evaluated successfully. Exiting.")
        sys.exit(1)

    save_summary(all_metrics)
    generate_graphs(all_metrics)
    print_summary(all_metrics)

    logger.info(f"Complete in {round(time.time()-t0, 1)}s. Results in '{RESULTS_DIR}/'.")


if __name__ == "__main__":
    main()